force-app/main/default/objects/Enchantment__c.object
<CustomObject>
    <description>Object representing enchantments on related products</description>
    <fields>
        <fullName>Enchantment_Rating__c</fullName>
        <description>The rating given to this enchantment</description>
        <label>Enchantment Rating</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product this enchantment is applied to</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Enchantments</relationshipLabel>
        <relationshipName>Enchantments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enchantment</label>
    <nameField>
        <label>Enchantment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enchantments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Enchantment_Rating__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The sum of all of the enchantment ratings of the enchantments on this product.</description>
        <label>Enchantment Rating</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EnchantmentTriggerHandler.cls
public with sharing class EnchantmentTriggerHandler {

    public static void updateParentEnchantmentScore(List<Enchantment__c> changeList) {
        //create idSet of ids of products that are related to our changelist enchantments
        Set<Id> idSet = new Set<Id>();
        for (Enchantment__c curEnchantment : changeList) {
            idSet.add(curEnchantment.Product__c);
        }

        //select all products in our idSet and return their list of enchantments too.
        List<Product2> parentProductList = [SELECT name, (SELECT name, enchantment_rating__c FROM Enchantments__r) FROM Product2 WHERE Id IN :idSet];

        //using normal for loop in order to modify parentProductList during iteration
        //modify enchantment rating of products to be sum of enchantment ratings of their enchantments
        for (Integer i = 0; i < parentProductList.size(); i++) {
            Double rollingSum = 0;
            Product2 curProduct = parentProductList.get(i);

            //add up enchantment ratings of enchantments on curProduct
            for (Enchantment__c curEnchantment : curProduct.Enchantments__r) {
                rollingSum += curEnchantment.Enchantment_Rating__c;
            }

            curProduct.Enchantment_Rating__c = rollingSum;
        }

        //commit changes to products
        UPDATE parentProductList;
    }
}